services:
  - type: web
    name: zeki-bot
    runtime: node
    repo: https://github.com/Sunay16018/zeki_bot
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: PORT
        value: 8080
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
